sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
    - REPO="webfirmframework/wff"
    - CI_HOME=`pwd`/$REPO
script: build.sh

install: mvn -B install -U -DskipTests=true

script: mvn -B verify -U -Dmaven.javadoc.skip=true
